#!/bin/sh
# Script to parse SystemVersion.plist to get the OS version.
# See: http://apple.stackexchange.com/q/39898/22781
ex -s +'%s/<[^>].\{-}>//ge' +'%s/\s\+//e' +'%norm J' +'g/^$/d' +%p +q! /System/Library/CoreServices/SystemVersion.plist
